name: Tagging
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

env:
  GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

permissions:
  contents: write  # 레포지토리 내용 수정 권한 추가

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0  # 태그 접근을 위해 전체 기록을 가져옴

      # 태그 버전 추출
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # build.gradle 버전 업데이트
      - name: Update version in build.gradle
        run: |
          sed -i "s/VERSION = '[0-9]\+\.[0-9]\+\.[0-9]\+'/VERSION = '${{ env.VERSION }}'/g" build.gradle

      - name: Set up JDK 11
        uses: actions/setup-java@main
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      # GPG 키 설정
      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          GPG_KEYID: ${{ secrets.SIGNING_KEY_ID }}
        run: |
          # GPG 키 임포트
          echo "$GPG_PRIVATE_KEY" | base64 -d > private.key
          gpg --batch --import private.key
          
          # secring.gpg 생성
          gpg --export-secret-keys --pinentry-mode loopback --passphrase "$SIGNING_PASSWORD" > secring.gpg
          
          # GPG 설정
          echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf
          echo "keyid-format 0xlong" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "default-key $GPG_KEYID" >> ~/.gnupg/gpg.conf
          
          # 키 확인
          gpg --list-secret-keys
          
          # 파일 정리
          rm private.key
          
          # secring.gpg 파일 위치 확인
          ls -la secring.gpg

      - name: Build and Publish
        uses: gradle/gradle-build-action@main
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_KEYID: ${{ secrets.SIGNING_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
        with:
          gradle-version: wrapper
          arguments: |
            publishToMavenCentral 
            --no-daemon 
            -PmavenCentralUsername=${{ env.MAVEN_USERNAME }} 
            -PmavenCentralPassword=${{ env.MAVEN_PASSWORD }} 
            -Psigning.keyId=${{ env.GPG_KEYID }} 
            -Psigning.password=${{ env.GPG_PASSPHRASE }}
            -Psigning.secretKeyRingFile=secring.gpg

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ⬆️Update version to ${{ env.VERSION }}
          branch: main
          file_pattern: build.gradle
          commit_author: joony.kim <bestheroz@users.noreply.github.com>
