name: Tagging
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0  # 태그 접근을 위해 전체 기록을 가져옴

      # 태그 버전 추출
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # build.gradle 버전 업데이트
      - name: Update version in build.gradle
        run: |
          sed -i "s/VERSION = '[0-9]\+\.[0-9]\+\.[0-9]\+'/VERSION = '${{ env.VERSION }}'/g" build.gradle

      # 변경사항 커밋
      - name: Commit version update
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add build.gradle
          git commit -m "chore: update version to ${{ env.VERSION }}"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          branch: main

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      # GPG 키 설정
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 -d > secring.gpg


      - name: build with Publish
        uses: gradle/gradle-build-action@main
        with:
          gradle-version: wrapper
          arguments: publishToMavenCentral --no-daemon \
            -PmavenCentralUsername="$MAVEN_USERNAME" \
            -PmavenCentralPassword="$MAVEN_PASSWORD" \
            -Psigning.keyId="$GPG_KEYID" \
            -Psigning.password="$GPG_PASSPHRASE" \
            -Psigning.secretKeyRingFile=secring.gpg
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_KEYID: ${{ secrets.SIGNING_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
