name: Tagging

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'  # 예: 0.1.2 형식의 태그

env:
  GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

permissions:
  contents: write  # 레포지토리 내용 수정 권한 추가

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 저장소 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 태그 접근을 위해 전체 기록을 가져옴

      # 2. 태그 버전 추출
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 3. build.gradle 버전 업데이트
      - name: Update version in build.gradle
        run: |
          sed -i "s/VERSION = '[0-9]\+\.[0-9]\+\.[0-9]\+'/VERSION = '${{ env.VERSION }}'/g" build.gradle

      # 4. JDK 11 설정
      - name: Set up JDK 11
        uses: actions/setup-java@main
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      # 5. GPG 키 설정 (In-Memory PGP 키 사용)
      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf
          echo "keyid-format 0xlong" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          gpg --list-keys
          echo "default-key $SIGNING_KEY_ID" >> ~/.gnupg/gpg.conf

      # 6. Maven Central에 배포
      - name: Build and Publish
        uses: gradle/actions/setup-gradle@main
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        with:
          gradle-version: wrapper
          arguments: |
            publishToMavenCentral 
            --no-daemon 
            -PmavenCentralUsername=${{ env.MAVEN_USERNAME }} 
            -PmavenCentralPassword=${{ env.MAVEN_PASSWORD }} 
            -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} 
            -Psigning.password=${{ env.SIGNING_PASSWORD }}

      # 7. build.gradle 변경 사항 커밋
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "⬆️Update version to ${{ env.VERSION }}"
          branch: main
          file_pattern: build.gradle
          commit_author: "joony.kim <bestheroz@users.noreply.github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
