name: test
on: [ push ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up JDK 11
        uses: actions/setup-java@main
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          gradle-version: wrapper
          arguments: assemble --no-daemon -Dspring.profiles.active=prod -x test
