name: test
on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]

env:
  GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

permissions:
  contents: write  # 레포지토리 내용 수정 권한 추가

jobs:
  spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up JDK 11
        uses: actions/setup-java@main
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main

      - name: Build with Gradle
        run: ./gradlew check jar --no-daemon

  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 11
        uses: actions/setup-java@main
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Build with Gradle
        run: ./gradlew test jacocoTestReport --no-daemon
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@main
        with:
          default_author: github_actions
          message: 'Update coverage badge'
          add: '*.svg'
